### ISSUE TITLE
App with powerplant register does not work on wam-dev server

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#61] opened 2019-07-09 21:40 UTC
The content of #43 does not work when pushed to the wam-dev server.

**Comment by christian-rli** [comment] 2019-07-29 16:40
It works on the server now... hold on. After checking again I have to state that it's still not working on the server.

**Comment by christian-rli** [comment] 2019-07-29 16:50
```
2019/07/29 14:20:49 [WARNING] Sending telemetry (attempt 1): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/29 14:20:58 [WARNING] Sending telemetry (attempt 2): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/29 14:21:25 [WARNING] Sending telemetry (attempt 3): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
2019/07/29 14:22:29 [ERROR] Sending telemetry: telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway
```
I would assume that this is related to the problem in #106

**Comment by christian-rli** [comment] 2019-07-30 13:10
I noticed that the error on the server only appears in large queries. Small queries are successful. That would support the idea that #106 is part of the same issue, because those queries also take a long time. 

So I would conclude that the problem comes with either file size, or with the duration of the query. @henhuy does this have to do with how either django or caddy were set up on the server? @nesnoj maybe you also have an idea.

**Comment by nesnoj** [comment] 2019-07-30 14:02
Is there a data limit set by the OEP which could restrict large queries? I haven't found anything related to quota, neither on the OEP site nor in the oedialect repo.
@MGlauer

**Comment by christian-rli** [comment] 2019-07-30 14:21
@MGlauer I think it is very unlikely to be the cause of the OEP in either way, because the queries do work on my local machine. It must have to do with our server setup. I'm going to investigate this further.

**Comment by christian-rli** [comment] 2019-07-30 14:32
@Bachibouzouk suggested this might contain a solution: https://github.com/caddyserver/caddy/issues/1944  although it looks like it would be a workaround for our specific problem.

**Comment by nesnoj** [comment] 2019-07-30 14:59
Does not seem to be related to me as I do not see the connection between a larger query and ipv6.
I'd rather dig for e.g. caddy caching...

**Comment by henhuy** [comment] 2019-08-01 13:19
I will dig into this...
Can you tell me what steps to take to reproduce the error?

**Comment by christian-rli** [comment] 2019-08-01 13:31
To reproduce the error: Go [here](https://wam.rl-institut.de:85/WAM_APP_FRED/) and click on the powerplant register tab. Leave the radio button on solar and select any state. After a while, the 502 error will come up in the network analysis.
Last time I did this selecting wind and clicking on Berlin produced a working query, but now I can't reproduce the working query, maybe because the network via vpn is too slow? In any case the api is rather slow.

**Comment by christian-rli** [comment] 2019-08-01 13:34
The same error occurs when you want to load the popup for any given weather point.  working queries include feedin-popups and the query for the closest weather points, which should technically be the same thing and only differ in size / duration.

**Comment by henhuy** [comment] 2019-08-01 13:49
Found it!
This is due to gunicorns worker timeout setting (set to 30s):
http://docs.gunicorn.org/en/latest/settings.html#timeout
Gunicorn states:

> Generally set to thirty seconds. Only set this noticeably higher if you’re sure of the repercussions for sync workers. For the non sync workers it just means that the worker process is still communicating and is not tied to the length of time required to handle a single request.

I don't know what timeout is needed?
I think, a starter should be to shorten query time and increase timeout only if necessary?!

**Comment by henhuy** [comment] 2019-08-01 14:13
I increased timeout to 60s - and now it starts working.
But anyway - I think this is not suitable for user experience...

**Comment by Bachibouzouk** [comment] 2019-08-01 14:31
The time the query takes depends on how much data the user want to retrieve from the OEDBunfortunately :(. Where the number of entries is too large, I would say a web app might not be the most efficient tool anyway. @christian-rli - we could/(should?) have a disclaimer that the app is not suitable for very large data queries, and redirect the user to the oep website maybe?

**Comment by christian-rli** [comment] 2019-08-01 15:02
Thank you @henhuy ! The size of the data is only part of the problem @Bachibouzouk . The time of the query to load 10 wind power plants in Berlin from the database is 52s from where I am. That's maybe because the table in the database is so large, but when thinking about it... I mean it's a database! Shouldn't any api just be a lot faster? You're right though, in any case there should be a disclaimer.

**Comment by nesnoj** [comment] 2019-08-01 15:10
> The time of the query to load 10 wind power plants in Berlin from the database is 52s from where I am

OMFG
Even with the new table in model_draft?
Do you think this is related to the postgis processing - do you query via geometry (e.g. bounding box with ST_CONTAINS)?

**Comment by christian-rli** [comment] 2019-08-01 15:28
... I haven't implemented the queries, but yes the new table is used. Weirdly enough 52s seems to be the time for any query now. 2696 wind power plants in Sachsen-Anhalt will take just as long. Only the really big queries take longer (solar power plants in Niedersachsen still won't work). I'm going to have a closer look at the queries.

**Comment by christian-rli** [comment] 2019-08-01 15:53
I noticed that running on my machine, the queries take a bit more than half the time compared to the server - which makes sense, if the server will first download data from the OEDB and then forward it to the user. That's probably bad style, but I think it's what's happening, because we "cheated" before, using a dedicated user account from within our IP-range and not the api. 

Looking at the query I did not see any transformations going on though. We query by several fields, but not geometry (NUTS region, scenario, generation_type and version). Our [query](https://github.com/rl-institut/WAM_APP_FRED/blob/05e6a1196a00b08b0b325119fbe460a7320ae9a9/serial_views.py#L157) in `serial_views.py`. Why it takes so long, I don't know.

**Comment by nesnoj** [comment] 2019-08-01 16:05
Some thoughts on the speed issue:

1. Replace loop by DF [here](https://github.com/rl-institut/WAM_APP_FRED/blob/05e6a1196a00b08b0b325119fbe460a7320ae9a9/serial_views.py#L189)  and convert to JSON afterwards. Something like
```
df = pd.read_sql_query(query.statement, session.bind, index_col='foo')
<do the shapely geom operations e.g. using something like df[col] = df[col].apply(lambda x: wkt_loads(x))>
df.to_json(...)
```
2. Remove unnecessary filters such as [version](https://github.com/rl-institut/WAM_APP_FRED/blob/05e6a1196a00b08b0b325119fbe460a7320ae9a9/serial_views.py#L181-L182) and have only the latest v0.4.5 in your table (I'd use v0.4.5 in the planned mview anyway, cf. https://github.com/rl-institut/WAM_APP_FRED/pull/111#issuecomment-515478749)
3. Add indexes for all cols in your filters
4. In case you use a geo operation such as ST_CONTAINS:
There's a nice way of speeding them up a lot:
```
SELECT whatever
FROM table1, table2
WHERE
  table1.geom && table2.geom AND
  ST_CONTAINS(table1.geom, table1.geom);
```
The [`&&`](https://postgis.net/docs/geometry_overlaps.html) operator checks for overlapping bounding boxes. This is a lot faster that `ST_CONTAINS` and in the query above it's executed first. ST_CONTAINS is only used if the bounding boxes overlap. So you could save a lot of time here..

There're surely some more stuff that could be optimized. If things don't help, you may consider to store the table locally..

**Comment by Bachibouzouk** [comment] 2019-08-02 21:57
OEDialect can't deal with ST_CONTAINS yet unfortunately! Which is why we couldn't use it (we used it at first with direct OEDB access)

**Comment by Bachibouzouk** [comment] 2019-08-02 21:59
Still, selecting for rows which nuts column is equal to a given nuts, should be fast...

**Comment by nesnoj** [comment] 2019-08-05 08:41
It depends on the count of datasets in `model_draft.openfred_powerplants` - with 39.1M it's supposed to be way faster with index.
A quick view reveals that there are no indexes at all (except for `pp_id` as it's automatically created for PK). I'd strongly recommend to add some to those cols you filter by, i.e. `version` (if you don't kick it), `nuts`, `scenario` and `generation_type`.
E.g.
```
CREATE INDEX ON model_draft.openfred_powerplants (nuts);
```
Also, it saves some CPU resources on the server ;)

**Comment by christian-rli** [comment] 2019-08-05 09:11
Thank you @nesnoj for all the feedback! I just deleted power plants of different versions in the table, which didn't improve performance noticeably. Then I created indices on the used columns and everything is much faster now! 5800 solar plants in Berlin now only take a couple seconds. I then created indices for our feed-in table as well.

**Comment by christian-rli** [comment] 2019-09-25 11:00
I analyzed the openfred_series table and it appears that there are no specific indexes. @Bachibouzouk could you briefly list the columns we use for our queries, so I can create an index? That might help a lot with performance and I can do it in a minute. You may then close this issue, because the original problem is solved, already.

**Comment by Bachibouzouk** [comment] 2019-09-26 05:14
There are defined [here](https://github.com/rl-institut/WAM_APP_FRED/blob/46ff547b690ee1a06784a0ff6ed6824a88e05f33/oep_models.py#L120). If I understood correctly, the indexes are there in the columns with names in the form of `*_id`. They are linked to other tables in oedb which have an index.

**Comment by jh-RLI** [comment] 2020-11-03 21:35
closed in https://github.com/rl-institut/WAM_APP_FRED/issues/106#issuecomment-518734978

**Closed as completed by jh-RLI** 2020-11-03 21:35 UTC
